name: Check S3 List
on:
  push:
    branches:
      - main

jobs:
  check_s3_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your desired AWS region

    - name: Check S3 Bucket Listing
      run: |
        # Replace "your-bucket-name" with the actual name of your S3 bucket
        aws s3 ls
  slackNotification:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      if: success()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Success'
        text: 'Build and deployment were successful!'
        username: 'GitHub Actions'
        icon_emoji: ':white_check_mark:'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        # SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        # SLACK_ICON: https://avatars.githubusercontent.com/u/1128392?s=48&v=4
        # SLACK_MESSAGE: 'Post Content :rocket:'
        # SLACK_TITLE: Build & Deployed Sucessfully
    - name: Slack Notification on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Failure'
        text: 'Build or deployment failed!'
        username: 'GitHub Actions'
        icon_emoji: ':x:'
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


