name: Check S3 List and Notify on Slack
on:
  push:
    branches:
      - main

jobs:
  check_s3_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your desired AWS region

    - name: Check S3 Bucket Listing
      run: |
        aws s3 ls

  slackNotification:
    needs: check_s3_list
    runs-on: ubuntu-latest
    if: always()  # This ensures the Slack notification is sent regardless of success or failure of the check_s3_list job
    steps:
    - name: Slack Notification
      if: ${{ needs.check_s3_list.result == 'success' }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Success'
        text: 'Congratulations! Your deployment was successful!'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON: https://avatars.githubusercontent.com/u/1128392?s=48&v=4
        SLACK_TITLE: Congratulations! Your deployment was successful
        SLACK_MESSAGE: 'demo'
        

    - name: Slack Notification on Failure
      if: ${{ needs.check_s3_list.result == 'failure' }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Failure'
        text: 'Oops! Deployment has failed!'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON: https://avatars.githubusercontent.com/u/1128392?s=48&v=4
        SLACK_TITLE: Oops! Deployment has failed
        SLACK_MESSAGE: 'demo-2'
