name: Check S3 List and Notify on Slack
on:
  push:
    branches:
      - main

jobs:
  check_s3_list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your desired AWS region

    - name: Check S3 Bucket Listing
      id: s3_list
      run: |
        if aws s3 ls; then
          echo "::set-output name=success::true"
        else
          echo "::set-output name=success::false"
        fi

  slackNotification:
    needs: check_s3_list
    runs-on: ubuntu-latest
    if: always()  # This ensures the Slack notification is sent regardless of success or failure of the check_s3_list job
    steps:
    - name: Slack Notification
      if: ${{ needs.check_s3_list.outputs.success == 'true' }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Success'
        text: 'Build and deployment were successful!'
        username: 'GitHub Actions'
        icon_emoji: ':white_check_mark:'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack Notification on Failure
      if: ${{ needs.check_s3_list.outputs.success == 'false' }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Failure'
        text: 'Build or deployment failed!'
        username: 'GitHub Actions'
        icon_emoji: ':x:'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
